bind-key c new-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"

set -g mouse on


# 设置 vi 风格的复制模式键位（如果你想使用 hjkl 移动，这是常见的搭配）
set -g mode-keys vi

# 取消默认的 Ctrl+空格 绑定（如果有冲突）
unbind-key -T copy-mode-vi C-Space

# 将 Ctrl+q 绑定为开始选择
bind-key -T copy-mode-vi C-q send-keys -X begin-selection


# 关键：让复制的内容自动进入系统剪贴板
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i"
